version: "3.3"
services:
  api:
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    build:
      dockerfile: ../../../apps/api/Dockerfile
      context: ./dist/apps/api
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL}
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      - ./data:/opt/app/data
      # - ./api/config:/opt/app/config
      # - ./api/src:/opt/app/src
    ports:
      - 1337:1337
    command: ["pnpm", "start"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
  client:
    container_name: sveltekit
    env_file: .env
    restart: unless-stopped
    build:
      dockerfile: ./apps/client/Dockerfile
      context: .
    environment:
      PRIVATE_BACKEND_API_URL: http://api:1337
      PORT: 4125
    ports:
      - 4125:4125
  db:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=0000