version: "3.3"
services:
  backend:
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    build:
      context: api
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      - ./data:/opt/app/data
      - ./api/config:/opt/app/config
      - ./api/src:/opt/app/src
    ports:
      - 1337:1337
    command: ["yarn", "start"]
